[package]
name = "bpaf_core"
version = "0.10.0"
edition = "2024"

[dependencies]

[features]
extradocs = []

[dev-dependencies]
pretty_assertions = "1.4"
bpaf = { path = "../bpaf", version = "0.10.0", features = ["derive", "extradocs"] }


[[example]]
name = "named"
path = "examples/named/combo.rs"

[[example]]
name = "named_derive"
path = "examples/named/derive.rs"

[[example]]
name = "any"
path = "examples/any/combo.rs"

[[example]]
name = "any_derive"
path = "examples/any/derive.rs"

[[example]]
name = "any_from_str"
path = "examples/any_from_str/combo.rs"

[[example]]
name = "any_from_str_derive"
path = "examples/any_from_str/derive.rs"

[[example]]
name = "fail"
path = "examples/fail/combo.rs"

[[example]]
name = "fail_derive"
path = "examples/fail/derive.rs"

[[example]]
name = "leftovers"
path = "examples/leftovers/combo.rs"

[[example]]
name = "leftovers_derive"
path = "examples/leftovers/derive.rs"

[[example]]
name = "literal"
path = "examples/literal/combo.rs"

[[example]]
name = "literal_derive"
path = "examples/literal/derive.rs"

[[example]]
name = "positional"
path = "examples/positional/combo.rs"

[[example]]
name = "positional_derive"
path = "examples/positional/derive.rs"

[[example]]
name = "strict"
path = "examples/strict/combo.rs"

[[example]]
name = "strict_derive"
path = "examples/strict/derive.rs"

[[example]]
name = "posix"
path = "examples/posix/combo.rs"

[[example]]
name = "posix_derive"
path = "examples/posix/derive.rs"

[[example]]
name = "pure"
path = "examples/pure/combo.rs"

[[example]]
name = "pure_derive"
path = "examples/pure/derive.rs"
