[package]
name = "bpaf_core"
version = "0.10.0"
edition = "2024"

[dependencies]

[features]
extradocs = []

[dev-dependencies]
pretty_assertions = "1.4"
bpaf = { path = "../bpaf", version = "0.10.0", features = ["derive", "extradocs"] }


[[example]]
name = "named"
path = "examples/named/combo.rs"

[[example]]
name = "named_derive"
path = "examples/named/derive.rs"
