.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nested 1 "29 Nov 2022" -
.SH NAME

nested \- I am a program and I do things 3
.SH SYNOPSIS

\fBnested\fR \-\fBd\fR=\fID\fR \fIC\fR \fBCOMMAND\fR...

\fBnested\fR \fBcmd\fR \-\fBd\fR=\fIy\fR

\fBnested\fR \fBdmc\fR \-\fBk\fR=\fIx\fR
.SH DESCRIPTION
Sometimes they even work. 3
.br

Beware `\-d`, dragons be here 3
.br

.SH OPTIONS
.TP

\fB\-d\fR, \fB\-\-ddd\fR=\fID\fR
mystery arg
.TP

\fIC\fR
Mystery file
.SH AUTHORS
Michael Baykov <manpacket@gmail.com>
.SH "REPORTING BUGS"
https://github.com/pacak/bpaf
