.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH simple 1 Aug\ 2022 Michael\ Baykov\ <manpacket@gmail.com> asdf
.PP
.SH SYNOPSIS
.nf
\fBsimple\fP\fR \fP\fB\-d\fP\fR=\fP\fID\fP\fR \fP\fIC\fP\fR \fP\fICOMMAND ...\fP\fR
\fP\fBsimple\fP\fR \fP\fBcmd\fP\fR \fP\fB\-d\fP\fR=\fP\fI<y>\fP\fR
\fP\fBsimple\fP\fR \fP\fBdmc\fP\fR \fP\fB\-k\fP\fR=\fP\fI<x>\fP\fR
\fP
.fi
.SH SIMPLE\ 
.SH NAME
\fRsimple \- \fP\fRI am a program and I do things 3\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fB\-d\fP\fR=\fP\fID\fP\fR \fP\fIC\fP\fR \fP\fICOMMAND ...\fP
.PP
\fRSometimes they even work. 3\fP
.PP
.SS AVAILABLE\ POSITIONAL\ ITEMS:
.TP
\fIC\fP
\fRMystery file\fP
.PP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fP\fR, \fP\fB\-\-ddd\fP\fR=\fP\fID\fP
\fRmystery arg\fP
.PP
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBcmd\fP
\fRI am a program and I do things\fP
.PP
.TP
\fBdmc\fP\fR, \fP\fBd\fP
\fRI am a program and I do things 2\fP
.PP
.PP
\fRBeware `\-d`, dragons be here 3\fP
.SH SIMPLE\ CMD\ 
.SH NAME
\fRsimple \- \fP\fRI am a program and I do things 3\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBcmd\fP\fR \fP\fB\-d\fP\fR=\fP\fI<y>\fP
.PP
\fRSometimes they even work. 3\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fP\fR=\fP\fI<y>\fP
\fRdragon\fP
.PP
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
\fRBeware `\-d`, dragons be here 3\fP
.SH SIMPLE\ DMC\ 
.SH NAME
\fRsimple \- \fP\fRI am a program and I do things 3\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBdmc\fP\fR \fP\fB\-k\fP\fR=\fP\fI<x>\fP
.PP
\fRSometimes they even work. 3\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-k\fP\fR=\fP\fI<x>\fP
\fRkraken\fP
.PP
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
\fRBeware `\-d`, dragons be here 3\fP