.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH simple 1 Aug\ 2022 Michael\ Baykov\ <manpacket@gmail.com> asdf
.SH NAME
\fRsimple \- \fP\fRI am a program and I do things\fP
.SH SYNOPSIS
\fBsimple\fP\fR [\fP\fB\-d\fP\fR]\fP
.PP
\fRSometimes they even work.\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fP\fR, \fP\fB\-\-kraken\fP
\fRUnleash the kraken\fP
.PP
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
\fRBeware `\-d`, dragons be here\fP