.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH simple 1 Aug\ 2022 Michael\ Baykov\ <manpacket@gmail.com> asdf
.PP
.SH SYNOPSIS
.nf
\fBsimple\fP\fR \fP\fICOMMAND ...\fP\fR
\fP\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fICOMMAND ...\fP\fR
\fP\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fICOMMAND ...\fP\fR
\fP\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fBlvl3\fP\fR \fP\fICOMMAND ...\fP\fR
\fP\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fBlvl3\fP\fR \fP\fBlvl4\fP\fR \fP\fB\-k\fP\fR=\fP\fINAME\fP\fR
\fP
.fi
.SH SIMPLE\ 
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fICOMMAND ...\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl1\fP
\fRlvl 1 description\fP
.PP
.SH SIMPLE\ LVL1\ 
.SH NAME
\fRsimple \- \fP\fRlvl 1 description\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fICOMMAND ...\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl2\fP
\fRlvl 2 description\fP
.PP
.SH SIMPLE\ LVL1\ LVL2\ 
.SH NAME
\fRsimple \- \fP\fRlvl 2 description\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fICOMMAND ...\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl3\fP
\fRlvl 3 description\fP
.PP
.SH SIMPLE\ LVL1\ LVL2\ LVL3\ 
.SH NAME
\fRsimple \- \fP\fRlvl 3 description\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fBlvl3\fP\fR \fP\fICOMMAND ...\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl4\fP
\fRlvl 4 description\fP
.PP
.SH SIMPLE\ LVL1\ LVL2\ LVL3\ LVL4\ 
.SH NAME
\fRsimple \- \fP\fRlvl 4 description\fP
.SH SYNOPSIS
\fBsimple\fP\fR \fP\fBlvl1\fP\fR \fP\fBlvl2\fP\fR \fP\fBlvl3\fP\fR \fP\fBlvl4\fP\fR \fP\fB\-k\fP\fR=\fP\fINAME\fP
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-k\fP\fR=\fP\fINAME\fP
\fRUnleash the Kraken\fP
.PP
.TP
\fB\-h\fP\fR, \fP\fB\-\-help\fP
\fRPrints help information\fP
.PP
