.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nested 1 "29 Nov 2022" -
.SH NAME

nested
.SH SYNOPSIS

\fBnested\fR \fBCOMMAND\fR...

\fBnested\fR \fBlvl1\fR \fBCOMMAND\fR...

\fBnested lvl1\fR \fBlvl2\fR \fBCOMMAND\fR...

\fBnested lvl1 lvl2\fR \fBlvl3\fR \fBCOMMAND\fR...

\fBnested lvl1 lvl2 lvl3\fR \fBlvl4\fR [\-\fBk\fR]
.SH DESCRIPTION
.SH AUTHORS
Michael Baykov <manpacket@gmail.com>
.SH "REPORTING BUGS"
https://github.com/pacak/bpaf
