.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "app" "1" "\-" "\-" "\-"
.PP
.SH SYNOPSIS
.nf
\fBapp\fR \fICOMMAND\fR ...
\fBapp\fR \fBlvl1\fR \fICOMMAND\fR ...
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fICOMMAND\fR ...
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fBlvl3\fR \fICOMMAND\fR ...
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fBlvl3\fR \fBlvl4\fR \fB\-k\fR=\fINAME\fR
.fi
.SH app\ 
.SH SYNOPSIS
\fBapp\fR \fICOMMAND\fR ...
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl1\fR
lvl 1 description
.PP
.SH app lvl1\ 
.SH NAME
\fRapp lvl1 \- \fPlvl 1 description
.SH SYNOPSIS
\fBapp\fR \fBlvl1\fR \fICOMMAND\fR ...
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl2\fR
lvl 2 description
.PP
.SH app lvl1 lvl2\ 
.SH NAME
\fRapp lvl1 lvl2 \- \fPlvl 2 description
.SH SYNOPSIS
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fICOMMAND\fR ...
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl3\fR
lvl 3 description
.PP
.SH app lvl1 lvl2 lvl3\ 
.SH NAME
\fRapp lvl1 lvl2 lvl3 \- \fPlvl 3 description
.SH SYNOPSIS
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fBlvl3\fR \fICOMMAND\fR ...
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBlvl4\fR
lvl 4 description
.PP
.SH app lvl1 lvl2 lvl3 lvl4\ 
.SH NAME
\fRapp lvl1 lvl2 lvl3 lvl4 \- \fPlvl 4 description
.SH SYNOPSIS
\fBapp\fR \fBlvl1\fR \fBlvl2\fR \fBlvl3\fR \fBlvl4\fR \fB\-k\fR=\fINAME\fR
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-k\fR=\fINAME\fR
Unleash the Kraken
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
