[package]
name = "bpaf_derive"
version.workspace = true
edition.workspace = true
categories = ["command-line-interface"]
description = "Derive macros for bpaf Command Line Argument Parser"
keywords = ["args", "arguments", "cli", "parser", "parse"]
authors.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true

[lib]
name = "bpaf_derive"
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
