.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "simple" "1" "Jul 2026" "pacak" "the bing thing"
.PP
.SH SYNOPSIS
.nf
\fBsimple\fR \fB\-d\fR=\fID\fR \fIC\fR \fICOMMAND\fR ...
\fBsimple\fR \fBcmd\fR \fB\-d\fR=\fI<y>\fR
\fBsimple\fR \fBdmc\fR \fB\-k\fR=\fI<x>\fR
.fi
.SH simple\ 
.SH NAME
\fRsimple \- \fPI am a program and I do things 3
.SH SYNOPSIS
\fBsimple\fR \fB\-d\fR=\fID\fR \fIC\fR \fICOMMAND\fR ...
.PP
Sometimes they even work. 3
.SS AVAILABLE\ POSITIONAL\ ITEMS:
.TP
\fIC\fR
Mystery file
.PP
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fR, \fB\-\-ddd\fR=\fID\fR
mystery arg
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
.SS AVAILABLE\ COMMANDS:
.TP
\fBcmd\fR
I am a program and I do things
.PP
.TP
\fBdmc\fR, \fBd\fR
I am a program and I do things 2
.PP
Beware `\-d`, dragons be here 3
.SH simple cmd\ 
.SH NAME
\fRsimple cmd \- \fPI am a program and I do things
.SH SYNOPSIS
\fBsimple\fR \fBcmd\fR \fB\-d\fR=\fI<y>\fR
.PP
Sometimes they even work. 1
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fR=\fI<y>\fR
dragon
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
Beware `\-d`, dragons be here 1
.SH simple dmc\ 
.SH NAME
\fRsimple dmc \- \fPI am a program and I do things 2
.SH SYNOPSIS
\fBsimple\fR \fBdmc\fR \fB\-k\fR=\fI<x>\fR
.PP
Sometimes they even work. 2
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-k\fR=\fI<x>\fR
kraken
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
Beware `\-d`, dragons be here 2
