.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "simple" "1" "Jul 2026" "pacak" "the bing thing"
.SH NAME
\fRsimple \- \fPI am a program and I do things
.SH SYNOPSIS
\fBsimple\fR [\fB\-d\fR] \fB\-\-user\fR=\fIUSER\fR
.PP
Sometimes they even work.
.SS AVAILABLE\ OPTIONS:
.TP
\fB\-d\fR, \fB\-\-kraken\fR
Unleash the kraken
.PP
.TP
\fB\-\-user\fR=USER
Log in as this user
.br
Uses environment variable \fBUSER\fR
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help information
.PP
Beware `\-d`, dragons be here
