//! Very basic derive example

#![allow(dead_code)]

use bpaf::*;

#[derive(Clone, Debug, Bpaf)]
#[bpaf(options, version)]
/// Accept speed and distance, print them
struct SpeedAndDistance {
    /// Dpeed in KPH
    speed: f64,
    /// Distance in miles
    distance: f64,
}

fn main() {
    // function options is generated by #[derive(Bpaf)] macro
    let opts = speed_and_distance().run();
    println!("Options: {:?}", opts);
}
