[package]
name = "docs2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpaf = { path = "../", features = ["autocomplete", "derive"] }
pretty_assertions = "1.3"
comptester = { path = "../comptester/", optional = true }

[build-dependencies]
shell-words = "1.1.0"
