use crate::{
    Ctx, Error, Item, Name, Parser, VKind, Visited, Visitor,
    console_writer::Style,
    traits::{Leaf, VisitGroup},
    visitors::help::Place,
};

#[cfg_attr(test, derive(Eq, PartialEq))]
#[derive(Debug, Copy, Clone)]
pub(crate) enum Block {
    Start(Place),
    EndSection,
    /// Open a section without adjusting the place. Needed for the nested parser
    Same,
}

pub const T: &str = Style::Text.ansi();
pub const L: &str = Style::Literal.ansi();
pub const H: &str = Style::Header.ansi();

impl TryFrom<u32> for Block {
    type Error = ();

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            12 => Ok(Block::Start(Place::Named)),
            13 => Ok(Block::Start(Place::Pos)),
            14 => Ok(Block::Start(Place::Command)),
            15 => Ok(Block::Start(Place::Section)),
            16 => Ok(Block::EndSection),
            17 => Ok(Block::Start(Place::Descr)),
            18 => Ok(Block::Start(Place::Usage)),
            19 => Ok(Block::Start(Place::Header)),
            20 => Ok(Block::Start(Place::Footer)),
            21 => Ok(Block::Same),
            _ => Err(()),
        }
    }
}

pub const NAMED: &str = "\u{1B}[12m";
pub const POS: &str = "\u{1B}[13m";
pub const CMD: &str = "\u{1B}[14m";
pub const CUSTOM: &str = "\u{1B}[15m";
pub const END: &str = "\u{1B}[16m";
pub const DESCR: &str = "\u{1B}[17m";
pub const USAGE: &str = "\u{1B}[18m";
pub const HEADER: &str = "\u{1B}[19m";
pub const FOOTER: &str = "\u{1B}[20m";
pub(crate) const SAME: &str = "\u{1B}[21m";

/// Wraps a parser and replaces its help output with a static string.
pub struct HelpLiteral<P> {
    pub(crate) inner: P,
    pub(crate) text: &'static str,
}

impl<P: Parser> Parser for HelpLiteral<P> {
    type Output = P::Output;

    fn eval<'p>(
        &'p self,
        ctx: Ctx<'p>,
    ) -> impl std::future::Future<Output = Result<P::Output, Error>> {
        self.inner.eval(ctx)
    }

    fn visit<'a>(&'a self, visitor: &mut dyn Visitor<'a>) {
        if visitor.identify() == VKind::Help {
            visitor.item(Item::Rendered { text: self.text });
        } else {
            self.inner.visit(visitor)
        }
    }
}

impl<P: Leaf> Leaf for HelpLiteral<P> {}

/// A parser whose help text is generated by a closure over [`HelpItem`]s.
///
/// Created with [`Parser::help_callback`].
pub struct HelpCallback<P, F> {
    pub(crate) inner: P,
    pub(crate) cb: F,
}

impl<P: Parser, F: Fn(HelpItems) -> String> Parser for HelpCallback<P, F> {
    type Output = P::Output;

    fn eval<'p>(
        &'p self,
        ctx: Ctx<'p>,
    ) -> impl std::future::Future<Output = Result<P::Output, Error>> {
        self.inner.eval(ctx)
    }

    fn visit<'a>(&'a self, visitor: &mut dyn Visitor<'a>) {
        if visitor.identify() == VKind::Help {
            let items = collect_help_items(&self.inner);
            visitor.item(Item::Rendered {
                text: &(self.cb)(HelpItems(items)),
            });
        } else {
            self.inner.visit(visitor)
        }
    }
}

pub struct HelpItems<'a>(Vec<HelpItem<'a>>);

impl<'a> std::fmt::Debug for HelpItems<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.as_slice().fmt(f)
    }
}

impl std::fmt::Display for HelpItems<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for item in &self.0 {
            writeln!(f, "{item}")?;
        }
        Ok(())
    }
}

impl<'a> HelpItems<'a> {
    pub fn flag(&self) -> Option<&FlagItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Flag(item)] => Some(item),
            _ => None,
        }
    }

    pub fn arg(&self) -> Option<&ArgItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Arg(item)] => Some(item),
            _ => None,
        }
    }

    pub fn positional(&self) -> Option<&PositionalItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Positional(item)] => Some(item),
            _ => None,
        }
    }

    pub fn command(&self) -> Option<&CommandItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Command(item)] => Some(item),
            _ => None,
        }
    }

    pub fn nested(&self) -> Option<&NestedItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Nested(item)] => Some(item),
            _ => None,
        }
    }

    pub fn section(&self) -> Option<&SectionItem<'a>> {
        match self.0.as_slice() {
            [HelpItem::Section(item)] => Some(item),
            _ => None,
        }
    }

    pub fn rendered(&self) -> Option<&str> {
        match self.0.as_slice() {
            [HelpItem::Rendered(text)] => Some(text.as_str()),
            _ => None,
        }
    }
}

impl<'a> IntoIterator for HelpItems<'a> {
    type Item = HelpItem<'a>;

    type IntoIter = <Vec<HelpItem<'a>> as IntoIterator>::IntoIter;

    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}

impl<'a, 's> IntoIterator for &'s HelpItems<'a> {
    type Item = &'s HelpItem<'a>;

    type IntoIter = std::slice::Iter<'s, HelpItem<'a>>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

impl<'a> AsRef<[HelpItem<'a>]> for HelpItems<'a> {
    fn as_ref(&self) -> &[HelpItem<'a>] {
        &self.0
    }
}

impl<'a> std::ops::IndexMut<usize> for HelpItems<'a> {
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

impl<'a> std::ops::Index<usize> for HelpItems<'a> {
    type Output = HelpItem<'a>;

    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl<P: Leaf, F> Leaf for HelpCallback<P, F> {}

#[derive(Debug, Clone)]
pub enum HelpItem<'a> {
    Flag(FlagItem<'a>),
    Arg(ArgItem<'a>),
    Positional(PositionalItem<'a>),
    Command(CommandItem<'a>),
    Nested(NestedItem<'a>),
    Section(SectionItem<'a>),
    Rendered(String),
}

#[derive(Debug, Clone)]
pub struct FlagItem<'a> {
    pub(crate) named: &'a crate::Named,
}

impl<'a> FlagItem<'a> {
    pub fn help(&self) -> Option<&'static str> {
        self.named.help
    }

    pub fn names(&self) -> &[Name<'_>] {
        &self.named.names
    }
}

impl std::fmt::Display for FlagItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{NAMED}")?;
        if let Some(sl) = self.named.get_shortlong() {
            write!(f, "{sl:#}")?;
        }
        write!(f, "\t")?;
        if let Some(help) = self.named.help {
            write!(f, "{help}")?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct ArgItem<'a> {
    pub(crate) named: &'a crate::Named,
    pub(crate) meta: crate::Metavar,
}

impl<'a> ArgItem<'a> {
    pub fn help(&self) -> Option<&'static str> {
        self.named.help
    }

    pub fn names(&self) -> Vec<String> {
        self.named
            .all_names_long_first()
            .map(|n| n.to_string())
            .collect()
    }

    pub fn metavar(&self) -> &'static str {
        self.meta.0
    }
}

impl std::fmt::Display for ArgItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{NAMED}")?;
        if let Some(sl) = self.named.get_shortlong() {
            write!(f, "{sl:#}")?;
            write!(f, "={}", self.meta)?;
        }
        write!(f, "\t")?;
        if let Some(help) = self.named.help {
            write!(f, "{help}")?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct PositionalItem<'a> {
    pub(crate) meta: crate::Metavar,
    pub(crate) help: Option<&'a str>,
}

impl<'a> PositionalItem<'a> {
    pub fn help(&self) -> Option<&'a str> {
        self.help
    }

    pub fn metavar(&self) -> &'static str {
        self.meta.0
    }
}

impl std::fmt::Display for PositionalItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{POS}")?;
        write!(f, "    {}", self.meta)?;
        write!(f, "\t")?;
        if let Some(help) = self.help {
            write!(f, "{help}")?;
        }
        Ok(())
    }
}

#[derive(Clone)]
pub struct CommandItem<'a> {
    pub(crate) names: &'a [crate::Lit<'static>],
    pub(crate) help: Option<&'a str>,
    pub(crate) inner: &'a dyn Visited,
}

impl<'a> CommandItem<'a> {
    pub fn help(&self) -> Option<&'a str> {
        self.help
    }

    pub fn names(&self) -> Vec<String> {
        self.names.iter().map(|n| n.to_string()).collect()
    }

    pub fn items(&self) -> Vec<HelpItem<'a>> {
        collect_help_items(self.inner)
    }
}

impl std::fmt::Debug for CommandItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CommandItem")
            .field("names", &self.names())
            .field("help", &self.help)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Display for CommandItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{CMD}")?;
        let name = self
            .names
            .iter()
            .map(|n| n.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        write!(f, "    {name}")?;
        write!(f, "\t")?;
        if let Some(help) = self.help {
            write!(f, "{help}")?;
        }
        Ok(())
    }
}

#[derive(Clone)]
pub struct NestedItem<'a> {
    pub(crate) outer: &'a dyn Visited,
    pub(crate) inner: &'a dyn Visited,
}

impl<'a> Visited for NestedItem<'a> {
    fn vi<'c>(&'c self, v: &mut dyn Visitor<'c>) {
        v.item(Item::Nested {
            outer: self.outer,
            inner: self.inner,
        });
    }
}

impl<'a> NestedItem<'a> {
    pub fn items(&self) -> HelpItems<'a> {
        HelpItems(collect_help_items(self.inner))
    }

    pub fn usage(&self) -> String {
        let mut u = crate::visitors::usage::Usage::default();
        self.vi(&mut u);
        let mut result = String::new();
        u.render_to(&mut result);
        result
    }
}

impl std::fmt::Debug for NestedItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NestedItem").finish_non_exhaustive()
    }
}

struct NestedWriter<'w, 'i> {
    f: &'w mut std::fmt::Formatter<'i>,
    wrote: bool,
    usage: String,
}

impl Visitor<'_> for NestedWriter<'_, '_> {
    fn item<'t>(&mut self, item: Item<'_, 't>) {
        match item {
            Item::Flag { named } => {
                let Some(sl) = named.get_shortlong() else {
                    return;
                };
                _ = write!(self.f, "{NAMED}{sl:#} {}", self.usage);
                if let Some(help) = named.help {
                    _ = write!(self.f, "\t{help}");
                }
            }
            Item::Command { names, help, .. } => {
                let name = crate::visitors::help::lit_name(names);
                _ = write!(self.f, "{CMD}{name:#} {}", self.usage);
                if let Some(help) = help {
                    _ = write!(self.f, "\t{help}");
                }
            }
            _ => return,
        }
        self.wrote = true;
        _ = writeln!(self.f);
    }

    fn identify(&self) -> VKind {
        VKind::Help
    }

    fn push_group(&mut self, _: VisitGroup) {}

    fn pop_group(&mut self) {}
}

impl std::fmt::Display for NestedItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut u = crate::visitors::usage::Usage::default();
        self.inner.vi(&mut u);
        let mut usage = String::new();
        u.render_to(&mut usage);

        let mut nw = NestedWriter {
            f,
            wrote: false,
            usage,
        };
        self.outer.vi(&mut nw);

        let wrote = nw.wrote;
        if !wrote {
            return Ok(());
        }

        let items = self.items();
        let count = items.0.len();
        write!(f, "{SAME}")?;
        for (ix, inner) in items.0.iter().enumerate() {
            write!(f, "{inner}")?;
            if ix + 1 < count {
                writeln!(f)?;
            }
        }
        write!(f, "{END}")?;
        Ok(())
    }
}

#[derive(Clone)]
pub struct SectionItem<'a> {
    pub(crate) title: &'a str,
    pub(crate) descr: Option<&'a str>,
    pub(crate) inner: &'a dyn Visited,
}

impl<'a> SectionItem<'a> {
    pub fn title(&self) -> &'a str {
        self.title
    }

    pub fn descr(&self) -> Option<&'a str> {
        self.descr
    }

    pub fn items(&self) -> Vec<HelpItem<'a>> {
        collect_help_items(self.inner)
    }
}

impl std::fmt::Debug for SectionItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SectionItem")
            .field("title", &self.title)
            .field("descr", &self.descr)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Display for SectionItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "{CUSTOM}{H}{}{T}", self.title)?;
        if let Some(descr) = self.descr {
            f.write_str(descr)?;
        }
        Ok(())
    }
}

impl std::fmt::Display for HelpItem<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HelpItem::Flag(i) => i.fmt(f),
            HelpItem::Arg(i) => i.fmt(f),
            HelpItem::Positional(i) => i.fmt(f),
            HelpItem::Command(i) => i.fmt(f),
            HelpItem::Nested(i) => i.fmt(f),
            HelpItem::Section(i) => i.fmt(f),
            HelpItem::Rendered(i) => i.fmt(f),
        }
    }
}

fn collect_help_items<'a>(inner: &'a dyn Visited) -> Vec<HelpItem<'a>> {
    struct Collector<'a> {
        items: Vec<HelpItem<'a>>,
    }

    impl<'a> Visitor<'a> for Collector<'a> {
        fn item<'t>(&mut self, item: Item<'a, 't>) {
            match item {
                Item::OptionParser { .. } => {
                    panic!("HelpMap collector encountered Item::OptionParser")
                }
                Item::Flag { named } => {
                    self.items.push(HelpItem::Flag(FlagItem { named }));
                }
                Item::Arg { named, meta } => {
                    self.items.push(HelpItem::Arg(ArgItem { named, meta }));
                }
                Item::Positional {
                    meta,
                    help,
                    strict: _,
                } => {
                    self.items
                        .push(HelpItem::Positional(PositionalItem { meta, help }));
                }
                Item::Command { names, help, inner } => {
                    self.items
                        .push(HelpItem::Command(CommandItem { names, help, inner }));
                }
                Item::Nested { outer, inner } => {
                    self.items
                        .push(HelpItem::Nested(NestedItem { outer, inner }));
                }
                Item::Section {
                    title,
                    descr,
                    inner,
                } => {
                    self.items.push(HelpItem::Section(SectionItem {
                        title,
                        descr,
                        inner,
                    }));
                }
                Item::Rendered { text } => {
                    self.items.push(HelpItem::Rendered(text.to_string()));
                }
            }
        }

        fn identify(&self) -> VKind {
            VKind::Custom
        }

        fn push_group(&mut self, _: VisitGroup) {}
        fn pop_group(&mut self) {}
    }

    let mut collector = Collector { items: vec![] };
    inner.vi(&mut collector);
    collector.items
}

pub struct Section<'a>(pub &'a str);
impl std::fmt::Display for Section<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use crate::custom_help::CUSTOM;
        const H: &str = Style::Header.ansi();
        const R: &str = Style::Text.ansi();
        write!(f, "{CUSTOM}{H}{text}{R}", text = self.0)
    }
}
