#![allow(private_interfaces)] // Name is private at the moment
use std::ffi::OsString;

use crate::{
    Lit, Metavar, Name,
    arg::Adjacency,
    complete::{CompleteReply, CompleteReq, render_completions},
    utils::Vec1,
};

#[derive(Debug)]
pub enum Problem {
    Parse {
        value: Option<String>,
        error: String,
    },
    // TODO - pass Metavar?
    WrongArgument {
        name: Name<'static>,
        value: Option<OsString>,
    },
    Unconsumed {
        value: OsString,
    },
    Conflict {
        accepted: OsString,
        unexpected: Name<'static>,
    },

    ConflictPos {
        accepted: OsString,
        unexpected: OsString,
    },
    GuardFailed {
        message: &'static str,
        range: Option<OsString>,
    },
    OnlyOnce {
        name: Name<'static>,
    },
    OnlyOnceInGroup {
        group: String,
        name: char,
        ix: u32,
    },
    DidYouMean {
        target: Name<'static>,
        best: Name<'static>,
    },
    DidYouMeanCmd {
        target: String,
        best: String,
    },
    ExpectedFlag {
        name: Name<'static>,
        adj: Adjacency,
        value: OsString,
    },
    Static(&'static str),
    TryDDash {
        name: String,
    },
    Dynamic {
        err: String,
    },
}

impl std::fmt::Display for Problem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Problem::Parse { value: None, error } => {
                write!(f, "couldn't parse: {error}")
            }
            Problem::Parse {
                value: Some(value),
                error,
            } => {
                write!(f, "couldn't parse `{value}`: {error}")
            }
            Problem::Unconsumed { value } => {
                write!(
                    f,
                    "`{}` is not expected in this context",
                    value.to_string_lossy()
                )
            }
            Problem::Conflict {
                accepted,
                unexpected,
            } => {
                write!(
                    f,
                    "`{unexpected}` cannot be used at the same time as `{}`",
                    accepted.to_string_lossy(),
                )
            }

            Problem::ConflictPos {
                accepted,
                unexpected,
            } => {
                write!(
                    f,
                    "`{}` cannot be used at the same time as `{}`",
                    unexpected.to_string_lossy(),
                    accepted.to_string_lossy(),
                )
            }
            Problem::WrongArgument { name, value: None } => {
                write!(f, "`{name}` expects a value")
            }
            Problem::WrongArgument {
                name,
                value: Some(value),
            } => {
                let s = value.to_string_lossy();
                write!(
                    f,
                    "`{name}` requires an argument TODO, got a flag {s}, try {name}={s}"
                )
            }
            Problem::GuardFailed { message, range } => match range {
                Some(r) => write!(f, "`{}`: {message}", r.to_string_lossy()),
                None => f.write_str(message),
            },
            Problem::OnlyOnce { name } => {
                write!(
                    f,
                    "argument `{name}` cannot be used multiple times in this context"
                )
            }
            Problem::OnlyOnceInGroup { group, name, ix } => {
                write!(
                    f,
                    "can't parse `{name}` (item {ix}) while parsing `{group}` as a set of short flags"
                )
            }
            Problem::DidYouMean { target, best } => {
                write!(f, "no such flag: `{target}`, did you mean `{best}`?")
            }
            Problem::DidYouMeanCmd { target, best } => {
                write!(f, "no such command: `{target}`, did you mean `{best}`?")
            }
            Problem::ExpectedFlag { name, adj, value } => {
                write!(
                    f,
                    "the app can accept `{name}` as a flag, but got `{name}{adj}{}`",
                    value.to_string_lossy()
                )
            }
            Problem::Static(msg) => write!(f, "{msg}"),
            Problem::TryDDash { name } => {
                write!(
                    f,
                    "no such flag: `-{name}` (with one dash), did you mean `--{name}`?"
                )
            }
            Problem::Dynamic { err } => write!(f, "{err}"),
        }
    }
}

#[derive(Debug)]
pub enum Error {
    Missing(Vec1<MissingItem>),
    CompReply(Vec1<CompleteReply>),
    /// Generated by the executor and hopefully handled by the user with .complete()
    CompReq(CompleteReq),
    /// `u32` describes the index where problem occurs - we want to try to report
    /// earliest possible issue
    Problem(u32, Problem),
    Final(ParseFailure),
    Silent(&'static str),
}

impl Error {
    pub(crate) const OUTCONSUMED: Self =
        Error::Silent("Task was terminated because alternative branch consumed more");
}

#[derive(Debug, Clone)]
pub enum MissingItem {
    Named {
        name: Name<'static>,
        meta: Option<Metavar>,
    },
    Pos {
        meta: Metavar,
    },
    Lit {
        value: Lit<'static>,
    },
}

impl std::fmt::Display for MissingItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MissingItem::Named { name, meta: None } => write!(f, "missing `{name}`"),
            MissingItem::Named {
                name,
                meta: Some(meta),
            } => write!(f, "missing `{name} {meta}`"),
            MissingItem::Pos { meta } => write!(f, "missing `{meta}`"),
            MissingItem::Lit { value } => write!(f, "missing `{value}`"),
        }
    }
}

#[derive(Debug, Clone)]
pub enum ParseFailure {
    Stdout(String),
    Stderr(String),
}

impl From<ParseFailure> for Error {
    fn from(value: ParseFailure) -> Self {
        Error::Final(value)
    }
}

#[inline(never)]
#[cold]
#[track_caller]
fn unwrap_failed(msg: &str, error: &str) -> ! {
    panic!("{msg}: {error:?}");
}
impl ParseFailure {
    #[track_caller]
    pub fn unwrap_stdout(self) -> String {
        match self {
            ParseFailure::Stdout(s) => s,
            ParseFailure::Stderr(e) => {
                unwrap_failed("Called `ParseFailure::unwrap_stdout()` on Stderr", &e)
            }
        }
    }

    #[track_caller]
    pub fn unwrap_stderr(self) -> String {
        match self {
            ParseFailure::Stderr(s) => s,
            ParseFailure::Stdout(e) => {
                unwrap_failed("Called `ParseFailure::unwrap_stderr()` on Stdout", &e)
            }
        }
    }
}

impl From<Error> for ParseFailure {
    fn from(value: Error) -> Self {
        match value {
            Error::Missing(vec1) => {
                let m = &vec1.as_slice()[0];
                ParseFailure::Stderr(m.to_string())
            }
            Error::CompReply(items) => ParseFailure::Stdout(render_completions(items)),
            Error::CompReq(_) => ParseFailure::Stdout(String::new()),
            Error::Problem(_, problem) => ParseFailure::Stderr(problem.to_string()),
            Error::Final(parse_failure) => parse_failure,
            Error::Silent(reason) => {
                ParseFailure::Stderr(format!("Internal error, got unexpected silent {reason}"))
            }
        }
    }
}

impl Error {
    pub(crate) fn combine(self, e2: Error) -> Error {
        match (self, e2) {
            (e @ Error::Final(_), _) | (_, e @ Error::Final(_)) => e,
            (Error::Silent(_), e) | (e, Error::Silent(_)) => e,
            (Error::CompReply(c1), Error::CompReply(c2)) => Error::CompReply(c1 + c2),
            (e @ Error::CompReply(_), _) | (_, e @ Error::CompReply(_)) => e,
            (e1 @ Error::Problem(o1, _), e2 @ Error::Problem(o2, _)) => {
                if o1 > o2 {
                    e2
                } else {
                    e1
                }
            }
            (e @ Error::Problem(..), _) | (_, e @ Error::Problem(..)) => e,
            (Error::CompReq(_), _) | (_, Error::CompReq(_)) => Error::CompReply(Default::default()),
            (Error::Missing(i1), Error::Missing(i2)) => Error::Missing(i1 + i2),
        }
    }

    pub(crate) fn can_catch(&self) -> bool {
        matches!(self, Error::Missing(_))
    }

    pub(crate) fn missing(item: MissingItem) -> Self {
        Self::Missing(Vec1::new(item))
    }

    /// Consume current error and append it to a growing collection in `dst`
    ///
    /// It exists to collect errors from multiple handles and designed to work with
    /// [`Result::map_err`]. We aggregate the best possible error inside an Option
    /// and fail with that if it is present
    pub fn append_to(self, dst: &mut Option<Error>) -> Self {
        *dst = Some(match dst.take() {
            Some(e) => e.combine(self),
            None => self,
        });
        Error::Silent("swapped by append_to")
    }

    /// Convert the error into a final version
    ///
    /// Used to convert errors from sub parsers (command parser, etc) that must take priority
    pub(crate) fn finalize_problems(self) -> Error {
        Error::Final(ParseFailure::from(self))
    }
}
