[package]
name = "satis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bpaf = { version = "0.9.23", features = ["derive"] }
cargo_metadata = { workspace = true }
diff = { workspace = true }
libc = { workspace = true }
mio = { workspace = true, features = ["os-ext", "os-poll"] }
pretty_assertions = { workspace = true }
ptyprocess = { workspace = true }
rayon = { workspace = true }
tempdir = { workspace = true }
vt100 = { workspace = true }
