[package]
name = "satis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.102" }
bpaf = { version = "0.9.23", features = ["derive"] }
libc = "0.2.182"
mio = { version = "1.1.1", features = ["os-ext", "os-poll"], default-features = false }
ptyprocess = "0.5.0"
tempdir = { version = "0.3.7" }
vt100 = "0.16.2"
cargo_metadata = "0.23"
pretty_assertions = "1.4"
diff = "0.1"
